version: "3"

services:
  bs-map-of-the-day:
    container_name: bs-map-of-the-day
    build:
      context: .
      dockerfile: Dockerfile
    image: bs-map-of-the-day
    env_file: .env
    ports:
      - 5000:5000
    volumes:
      - ./.db:/usr/src/app/.db/
